wip

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -4,19 +4,22 @@ FROM python:3.11-bullseye
 RUN set -eux \
   && apt-get update \
   && apt-get install -y sudo bash bash-completion git vim curl \
-    postgresql-client \
-  && apt-get clean
+    postgresql-client
 
 # ------------------------------ install nodejs ------------------------------ #
 RUN set -eux \
   && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
   && apt-get install -y nodejs
 
+# --------------------------------- clean up --------------------------------- #
+RUN set -eux && apt-get clean
+
 # --------------------------- create non root user --------------------------- #
 ARG USERNAME=dev
 ARG USER_UID=1001
 ARG USER_GID=$USER_UID
-RUN groupadd --gid $USER_GID $USERNAME \
+RUN set -eux \
+  && groupadd --gid $USER_GID $USERNAME \
   && useradd --uid $USER_UID --gid $USER_GID --groups sudo -m $USERNAME \
   && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
   && chmod 0440 /etc/sudoers.d/$USERNAME \
